# Inventário LocalStack — EC2 simulados via containers Docker
# Os containers expõem SSH nas portas mapeadas no docker-compose.yml

[api]
ec2-api ansible_host=127.0.0.1 ansible_port=2222

[db]
ec2-db ansible_host=127.0.0.1 ansible_port=2223

[all:vars]
ansible_python_interpreter=/usr/bin/python3
